term.clear()
term.setCursorPos(1,1)
term.setTextColor(colors.lightBlue)
print("Welcome to the TideOS Installer!")
sleep(1)
print()
print("Just a few notes before we begin:")
sleep(0.5)
print()
print("This OS was designed for CC: Tweaked. If you are using the original ComputerCraft or CC: Restitched, or any other version, this OS may not function properly.")
sleep(2.5)
print()
print("This installer downloads the proper OS files from the internet. If you don't have an internet connection, the installer will fail.")
sleep(1.5)
print()
print("With the preinstall stuff taken care of, let's go!")
